version: '3'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/home/pmarkaide/data/mysql
    ports:
      - "3306:3306"
    networks:
      - inception_network

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/pmarkaide/data/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/pmarkaide/data/wordpress
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - mariadb
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
