version: '3'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/pmarkaid/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception_network

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - /home/pmarkaid/data/wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - /home/pmarkaid/data/wordpress:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - mariadb
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
