version: '3'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception_network

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pmarkaid/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pmarkaid/data/wordpress
