version: '3'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/home/pmarkaide/data/mysql
    ports:
      - "3306:3306"

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - nginx_data:/home/pmarkaide/data/nginx
    ports:
      - "443:443"

volumes:
  mariadb_data:
  nginx_data:
